### ISSUE TITLE
npm test issue: TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by fyhao** [fyhao/tns-webform-client#286]
```
1) modFlow #setVar should able to setVar:
     TypeError: Cannot read property 'push' of undefined
      at FlowEngine.setContext (app\lib\modBrowser\modFlow.js:1:10318)
      at Object.ctx.createFlowEngine (test\testModFlow.js:21:42)
      at executeWebform (test\testModFlow.js:103:7)
      at Context.<anonymous> (test\testModFlow.js:123:3)
```

Checklist:
------
- [x] local npm test passed
- [x] Integration branch npm test passed
- [x] Staging branch real device passed, not affect other features

**Comment by fyhao** [comment]
Integration branch npm test passed
